### ISSUE TITLE
I need your Help, Please!

### ISSUE THREAD

**Issue by vnalexbr** [doctoroyy/edge-tts-as-a-service#1]
Hello, how are you today?

I'm trying to install on my droplet on digitalocean, but when I start with the command (gunicorn -w 4 -t 3600 -b 0.0.0.0:5000 main:app) my page doesn't look like tts.doctoroyy.net/ it doesn't appear to me and returns an error

Not Found
The requested URL was not found on the server. If you typed the URL manually, check your spelling and try again.

Could you help me?

I realize that also when. I run the command to see the folders I have, but neither src/ nor /public appears

(venv) root@vem-gold:/edge-tts-as-a-service# ls
Dockerfile README.md main.py start.sh vercel.json
LICENSE pycache requirements.txt test.mp3
(venv) root@vem-gold:/edge-tts-as-a-service#

and the command I used to download the repository was "git clone https://github.com/doctoroyy/edge-tts-as-a-service""

Thanks in advance for your help!
<img width="1419" alt="Screenshot 2024-08-22 at 17 44 35" src="https://github.com/user-attachments/assets/dcd31cf5-e8e0-4b3d-a3b9-f4a95cdd8689">

**Comment by vnalexbr** [comment]
Hello, how are you today?

I'm trying to install on my droplet on digitalocean, but when I start with the command (gunicorn -w 4 -t 3600 -b 0.0.0.0:5000 main:app) my page doesn't look like tts.doctoroyy.net/ it doesn't appear to me and returns an error

Not Found
The requested URL was not found on the server. If you typed the URL manually, check your spelling and try again.

Could you help me?

I realize that also when. I run the command to see the folders I have, but neither src/ nor /public appears

(venv) root@vem-gold:/edge-tts-as-a-service# ls
Dockerfile README.md main.py start.sh vercel.json
LICENSE pycache requirements.txt test.mp3
(venv) root@vem-gold:/edge-tts-as-a-service#

and the command I used to download the repository was "git clone https://github.com/doctoroyy/edge-tts-as-a-service""

Thanks in advance for your help!
<img width="1419" alt="360657008-dcd31cf5-e8e0-4b3d-a3b9-f4a95cdd8689" src="https://github.com/user-attachments/assets/971baecc-f0d0-45f9-80d6-3330de669b2a">

**Comment by doctoroyy** [comment]
`edge-tts-as-a-service` only provides an API service. If you're looking for a frontend, you can use [react-audio-stream-demo](https://github.com/doctoroyy/react-audio-stream-demo). 
Remember to modify the `REACT_APP_DEFAULT_API_PREFIX` variable in the `env` file.
